name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      # Skip post-install to avoid malicious scripts stealing PAT
      run: npm install
    - name: Post-install
      run: npm rebuild && npm run prepare --if-present
    - name: Test
      run: npm test
    - name: Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: ./release.sh
